### ISSUE TITLE
Ajustar "Tags"

### ISSUE THREAD

**Issue by gari01234** [LigaPeatonal/evaluando#5]
Ver cuáles etiquetas "Tags" se pueden ajustar al entorno urbano peatonal mexicano.

**Rampa peatonal:**
- Orientada al tránsito
- Pavimento de advertencia táctil ausente
- Empinada (mucha pendiente)
- Área de aproximación insuficiente
- Muy angosta
- Con desnivel

**Rampa peatonal ausente:**
- Hay una ruta alternativa en zona peatonal

**Obstáculo en banquetas:**
- Rampa de acceso a cochera
- Poste
- Árbol
- Vegetación
- Señalamiento
- Bote de basura, Contenedor de reciclaje
- Auto estacionado
- Material de construcción
- Extensión de cochera 
- Alcantarillas
- Teléfono público
- Publicidad
- Comercio ambulante

**Problemas en superficie:**
- Grietas
- Muy angosta
- Textura irregular
- Hoyo
- Charco

**No hay banqueta**

- Termina abruptamente
- La calle tiene una banqueta
- La calle no tiene banquetas
- Camino de tierra
- Plataforma única
- Es una calle peatonal

**Otro**

- Paso peatonal ausente
- No hay acceso a la parada de autobús
- Muro ciego

**Comment by jonfroehlich** [comment]
This is great @gari01234. Possible to also include English translations of these?
